kind: Deployment
metadata:
name: hello
labels:
  app: hello
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: hello
      tier: hello
  spec:
    containers:
    - name: hello
      image: singhshalini018/hello:latest
      ports:
      - containerPort: 5000
        name: hello