apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
    type: beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: user-api
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 5000
          name: hello



